### ISSUE TITLE
Wrong Stats

### ISSUE THREAD

**Issue by sgt502** [Mapaler/PADDashFormation#2]
When I use V + Nightmare as base card and added Guardian of the Imperial Nation, Athena as assist (at level 110), the stats on V + Nightmare reads as NaN for all stats, thus reading my team's stats also wrong, especially HP.

here's the link: https://bit.ly/301WTgj

**Comment by Mapaler** [comment]
This bug due to an increase of 120 levels of calculation. Appears when the assist's level > 99. Fixed at https://github.com/Mapaler/PADDashFormation/commit/19ba47fb03d76d930f8a8a8fcccdf0ff2a7c603b
I'm sorry I haven't seen this problem, until I found out on my own initiative. I don't know why lost the notification.
